-- PostgreSQL Database Setup Script for Virtual Interviewer Backend
-- This script creates the database and all required tables

-- Create the database (run this as a superuser)
-- CREATE DATABASE virtual_interviewer_db;
-- \c virtual_interviewer_db;

-- Enable UUID extension for generating unique identifiers
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Users Table - Contains login details
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    last_login TIMESTAMP WITH TIME ZONE
);

-- 2. Sessions Table - Contains session information
CREATE TABLE sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_name VARCHAR(100),
    session_type VARCHAR(50) DEFAULT 'interview', -- interview, practice, mock, etc.
    status VARCHAR(20) DEFAULT 'active', -- active, completed, paused, abandoned
    started_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ended_at TIMESTAMP WITH TIME ZONE,
    duration_minutes INTEGER,
    total_questions INTEGER DEFAULT 0,
    completed_questions INTEGER DEFAULT 0,
    session_metadata JSONB, -- Store additional session-specific data
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Conversations Table - Contains questions, LLM answers, and user responses
CREATE TABLE conversations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_id UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    question_number INTEGER NOT NULL,
    question_text TEXT NOT NULL,
    question_category VARCHAR(50), -- technical, behavioral, situational, etc.
    question_difficulty VARCHAR(20) DEFAULT 'medium', -- easy, medium, hard
    llm_generated_answer TEXT, -- The ideal answer generated by LLM
    user_answer TEXT, -- The user's actual answer
    user_answer_audio_url VARCHAR(500), -- Path to audio file if voice response
    answer_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    time_taken_seconds INTEGER, -- Time user took to answer
    llm_feedback TEXT, -- AI feedback on user's answer
    confidence_score DECIMAL(3,2), -- Score from 0.00 to 1.00
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Performance Table - Contains user performance analytics
CREATE TABLE performance (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_id UUID REFERENCES sessions(id) ON DELETE SET NULL,
    conversation_id UUID REFERENCES conversations(id) ON DELETE SET NULL,
    metric_type VARCHAR(50) NOT NULL, -- overall_score, communication, technical, confidence, etc.
    metric_value DECIMAL(5,2) NOT NULL, -- The actual score/value
    metric_max_value DECIMAL(5,2) DEFAULT 100.00, -- Maximum possible value
    metric_unit VARCHAR(20), -- percentage, seconds, count, etc.
    performance_category VARCHAR(50), -- speaking_speed, clarity, content_quality, etc.
    feedback_notes TEXT,
    improvement_suggestions TEXT,
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better performance
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_sessions_user_id ON sessions(user_id);
CREATE INDEX idx_sessions_status ON sessions(status);
CREATE INDEX idx_conversations_session_id ON conversations(session_id);
CREATE INDEX idx_conversations_question_number ON conversations(session_id, question_number);
CREATE INDEX idx_performance_user_id ON performance(user_id);
CREATE INDEX idx_performance_session_id ON performance(session_id);
CREATE INDEX idx_performance_metric_type ON performance(metric_type);

-- Create triggers to automatically update the updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_sessions_updated_at BEFORE UPDATE ON sessions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_conversations_updated_at BEFORE UPDATE ON conversations
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Create a function to calculate session duration
CREATE OR REPLACE FUNCTION calculate_session_duration()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.ended_at IS NOT NULL AND NEW.started_at IS NOT NULL THEN
        NEW.duration_minutes = EXTRACT(EPOCH FROM (NEW.ended_at - NEW.started_at)) / 60;
    END IF;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER calculate_duration_trigger BEFORE UPDATE ON sessions
    FOR EACH ROW EXECUTE FUNCTION calculate_session_duration();

-- Insert sample data (optional - remove in production)
INSERT INTO users (username, email, password_hash, first_name, last_name) VALUES
('john_doe', 'john.doe@example.com', '$2b$10$example_hash', 'John', 'Doe'),
('jane_smith', 'jane.smith@example.com', '$2b$10$example_hash', 'Jane', 'Smith');

-- Grant permissions (adjust as needed for your application)
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO your_app_user;
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO your_app_user;

-- Comments for documentation
COMMENT ON TABLE users IS 'Stores user login credentials and profile information';
COMMENT ON TABLE sessions IS 'Tracks interview/practice sessions for each user';
COMMENT ON TABLE conversations IS 'Records individual Q&A interactions within sessions';
COMMENT ON TABLE performance IS 'Stores detailed performance metrics and analytics';

COMMENT ON COLUMN users.password_hash IS 'Bcrypt hashed password';
COMMENT ON COLUMN sessions.session_metadata IS 'JSON field for storing additional session data';
COMMENT ON COLUMN conversations.confidence_score IS 'AI confidence in user answer quality (0.00-1.00)';
COMMENT ON COLUMN performance.metric_value IS 'The actual performance measurement value';
